$(document).ready(function()
{
  $(window).load(function()
  {
    $("#status").delay(495).fadeOut();
    $("#preload").delay(500).fadeOut();
   }); 
	$("#change_cover").click(function()
	{
	  $("#back_cover").show('slow');
	  $("#cover_btn").toggle('slow');
	  $(".b").animate('filter:blur(5px)');
	});
    $("#change_pro").click(function()
	{ 
	  $("#back_cover").show('slow');
	  $("#pro_btn").toggle('slow');
	});	
	$(".close").click(function()
	{
	  $("#back_cover").hide('slow');
	  $(".pic_insert").hide('slow');
	});	
  
 });  